# Generated by Django 5.1.1 on 2024-12-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='zopcode',
            new_name='zipcode',
        ),
    ]
